"""A standalone interactive viewer of recorded evidence, never labeled a live model UI."""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
b=json.loads((root/'evidence/final-baseline/results.json').read_text())
f=json.loads((root/'evidence/final-improved/results.json').read_text())
html='''<!doctype html><html lang="en"><meta charset="utf-8"><title>Harbor Evidence Review</title>
<style>body{font:20px Arial;margin:0;background:#f5f7fa;color:#102b46}header{padding:30px 48px;background:#0c294a;color:white}h1{margin:0 0 10px;font-size:36px}main{padding:24px 48px}select,button{font:inherit;padding:10px;margin-right:12px}section{display:grid;grid-template-columns:1fr 1fr;gap:30px}article{background:white;border-top:4px solid #1760ab;padding:22px}h2{font-size:26px;margin-top:0}pre{white-space:pre-wrap;font:18px/1.5 Consolas;max-height:230px;overflow:auto}.muted{font-size:16px;color:#526578}#question{font-size:27px;margin:20px 0}table{border-collapse:collapse;width:100%;background:white}td,th{text-align:left;padding:12px;border-bottom:1px solid #ccd6df}nav{margin-bottom:18px}.bad{color:#b23030}.good{color:#126644}</style>
<header><h1>Harbor Support Evidence Lab</h1><div>Recorded local Qwen2.5 0.5B runs · Synthetic documents · 14 September 2026</div></header>
<main><nav><button id="cases">Compare answers</button><button id="scores">Scores</button><button id="security">Security evidence</button></nav><div id="content"></div></main>
<script>const B=BASELINE,F=IMPROVED; const el=document.getElementById('content');
function esc(t){return String(t??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
function panel(r,label){return `<article><h2>${label}</h2><p>Retrieval: <b>${r.retrieval_pass?'PASS':'FAIL'}</b> &nbsp; Answer: <b>${r.generation_pass?'PASS':'FAIL'}</b></p><pre>${esc(r.actual.answer||r.actual.raw_model_output||'(no validated answer)')}</pre><p class="muted">Retrieved: ${esc(r.actual.retrieved_sources.join(', ')||'none')}</p><p class="muted">Citations: ${esc(r.actual.citations.join(', ')||'none')}</p><p class="bad">${esc(r.actual.error||'')}</p></article>`}
function show(i){document.getElementById('question').textContent=F.rows[i].question;document.getElementById('panels').innerHTML=panel(B.rows[i],'Naive baseline')+panel(F.rows[i],'Improved');document.getElementById('expected').textContent='Expected: '+F.rows[i].expected_answer}
function cases(){el.innerHTML='<label>Question <select id="pick">'+F.rows.map((r,i)=>`<option value="${i}">${r.id} · ${r.category}</option>`).join('')+'</select></label><p id="question"></p><section id="panels"></section><p id="expected"></p><p class="muted">Evidence replay, not a live model call. Use the CLI to reproduce the run. Errors count as failed answers.</p>';document.getElementById('pick').onchange=e=>show(+e.target.value);show(0)}
document.getElementById('cases').onclick=cases;
document.getElementById('scores').onclick=()=>{el.innerHTML='<h2>50 questions, two separate scores</h2><table><tr><th>Category</th><th>Baseline retrieval</th><th>Baseline answer</th><th>Improved retrieval</th><th>Improved answer</th></tr>'+['easy','synthesis','conflict','stale','must_refuse'].map(c=>'<tr><td>'+c+'</td>'+[B,F].map(d=>['retrieval_pass','generation_pass'].map(k=>'<td>'+d.rows.filter(r=>r.category===c&&r[k]).length+'/10</td>').join('')).join('')+'</tr>').join('')+'</table><p>Baseline 30/50 retrieval, 15/50 answers. Improved 50/50 retrieval, 38/50 answers.</p><p class="muted">The rubric checks terms and source IDs. This development set is not independent validation.</p>'};
document.getElementById('security').onclick=()=>{el.innerHTML='<h2>Owned local MCP server</h2><table><tr><th>Test</th><th>Before</th><th>After</th></tr><tr><td>Analyst A reads case B</td><td>Record and private note exposed</td><td>Case unavailable</td></tr><tr><td>1,000 calls in one simulated minute</td><td>1,000 accepted</td><td>20 accepted; 980 rejected</td></tr><tr><td>Override principal in tool arguments</td><td>Unchecked fixture</td><td>Only case_id is accepted</td></tr></table><p>10 regression tests passed, including actual JSON-RPC stdio transport.</p><p class="muted">Local process identity is not remote authentication. Restarting the process resets the quota.</p>'};cases();</script></html>'''
html=html.replace('BASELINE',json.dumps(b).replace('</','<\\/')).replace('IMPROVED',json.dumps(f).replace('</','<\\/'))
(root/'output/evidence-review.html').write_text(html,encoding='utf-8')
